# Generated by Django 2.1.3 on 2018-12-16 15:57

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181216_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumbnails'),
        ),
    ]
